server:
  port: 9090
  tomcat:
    connection-timeout: 180000
    max-connections: 200

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ip}:3306/honey2024?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: David080405
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

ip: localhost

file:
  download:
    dir: /Users/david/Desktop

blast:
  db:
    path: /Users/david/ref_viruses_rep_genomes
  output:
    file: ./result.txt
  executable: blastn





